#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-kiwisolver
Version  : 1.4.0
Release  : 36
URL      : https://files.pythonhosted.org/packages/de/a8/8c5ed1845bfdcf753ac13c3c6368c16df20a8a8ee3c06e5114eca83b9f0b/kiwisolver-1.4.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/de/a8/8c5ed1845bfdcf753ac13c3c6368c16df20a8a8ee3c06e5114eca83b9f0b/kiwisolver-1.4.0.tar.gz
Summary  : A fast implementation of the Cassowary constraint solver
Group    : Development/Tools
License  : BSD-3-Clause
Requires: pypi-kiwisolver-license = %{version}-%{release}
Requires: pypi-kiwisolver-python = %{version}-%{release}
Requires: pypi-kiwisolver-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(cppy)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(wheel)

%description
Welcome to Kiwi
===============
.. image:: https://travis-ci.org/nucleic/kiwi.svg?branch=main
:target: https://travis-ci.org/nucleic/kiwi
.. image:: https://github.com/nucleic/kiwi/workflows/Continuous%20Integration/badge.svg
:target: https://github.com/nucleic/kiwi/actions
.. image:: https://github.com/nucleic/kiwi/workflows/Documentation%20building/badge.svg
:target: https://github.com/nucleic/kiwi/actions
.. image:: https://codecov.io/gh/nucleic/kiwi/branch/main/graph/badge.svg
:target: https://codecov.io/gh/nucleic/kiwi
.. image:: https://readthedocs.org/projects/kiwisolver/badge/?version=latest
:target: https://kiwisolver.readthedocs.io/en/latest/?badge=latest
:alt: Documentation Status

%package license
Summary: license components for the pypi-kiwisolver package.
Group: Default

%description license
license components for the pypi-kiwisolver package.


%package python
Summary: python components for the pypi-kiwisolver package.
Group: Default
Requires: pypi-kiwisolver-python3 = %{version}-%{release}

%description python
python components for the pypi-kiwisolver package.


%package python3
Summary: python3 components for the pypi-kiwisolver package.
Group: Default
Requires: python3-core
Provides: pypi(kiwisolver)

%description python3
python3 components for the pypi-kiwisolver package.


%prep
%setup -q -n kiwisolver-1.4.0
cd %{_builddir}/kiwisolver-1.4.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1647355288
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-kiwisolver
cp %{_builddir}/kiwisolver-1.4.0/LICENSE %{buildroot}/usr/share/package-licenses/pypi-kiwisolver/ace4126f107c97f428124e67a02779b336f58099
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-kiwisolver/ace4126f107c97f428124e67a02779b336f58099

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
